// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookshelfRecord = { id: number, book_id: number, group_name: string, added_at: number, };
