// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadingProgressRecord = { id: number, book_id: number, chapter_order: number, page_index: number, last_read_at: number, updated_at: number, };
