// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookRecord = { id: bigint, website_book_id: bigint | null, path_num: bigint, title: string, filename: string, author: string, category: string, introduce: string, likes: bigint, word_count: bigint, page_count: bigint, created_at: bigint, updated_at: bigint, };
