// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookRecord = { id: number, website_book_id: number | null, path_num: number, title: string, filename: string, author: string, category: string, introduce: string, likes: number, word_count: number, page_count: number, created_at: number, updated_at: number, };
