// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookshelfRecord = { id: bigint, book_id: bigint, group_name: string, added_at: bigint, };
