// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChapterRecord = { id: number, book_id: number, title: string, url: string, chapter_order: number, word_count: number, };
