// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChapterRecord = { id: bigint, book_id: bigint, title: string, url: string, chapter_order: bigint, word_count: bigint, };
