// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单本书的爬取任务状态记录
 */
export type CrawlTaskRecord = { id: number, website_book_id: number, book_id: number | null, title: string, status: string, progress: number, chapters_total: number, chapters_done: number, error_message: string, trigger: string, started_at: number | null, finished_at: number | null, created_at: number, updated_at: number, };
