// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单本书的爬取任务状态记录
 */
export type CrawlTaskRecord = { id: bigint, website_book_id: bigint, book_id: bigint | null, title: string, status: string, progress: bigint, chapters_total: bigint, chapters_done: bigint, error_message: string, trigger: string, started_at: bigint | null, finished_at: bigint | null, created_at: bigint, updated_at: bigint, };
