// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadingGoalRecord = { id: number, daily_minutes: number, daily_chapters: number, updated_at: number, };
