// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadingGoalRecord = { id: bigint, daily_minutes: bigint, daily_chapters: bigint, updated_at: bigint, };
