// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadingSessionRecord = { id: bigint, book_id: bigint, chapter_order: bigint, duration_sec: bigint, chapters_read: bigint, started_at: bigint, ended_at: bigint, };
