// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadingProgressRecord = { id: bigint, book_id: bigint, chapter_order: bigint, page_index: bigint, last_read_at: bigint, updated_at: bigint, };
