// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadingSessionRecord = { id: number, book_id: number, chapter_order: number, duration_sec: number, chapters_read: number, started_at: number, ended_at: number, };
