// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SectionRecord = { id: bigint, chapter_id: bigint, book_id: bigint, url: string, content: string, section_order: bigint, };
