// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SectionRecord = { id: number, chapter_id: number, book_id: number, url: string, content: string, section_order: number, };
